/** 
 * All the types structure bellow was generated by the https://transform.tools/
 * using a `window.booking.env` object value gathered from a property page in
 * https://booking.com as base
 */

export interface BookingEnvData {
  isRetina: boolean
  b_gtt: string
  b_action: string
  b_secure_domain: string
  b_site_type: string
  b_site_type_id: string
  b_agent_is_no_robot: boolean
  b_agent_is_robot: boolean
  b_query_params_with_lang_no_ext: string
  b_query_params_with_lang_no_ext_enforce_lang_aid_currency: string
  b_travel_comm_url_with_lang: string
  b_calendar2: string
  BHDTJdReLGMeEcYPffcVDZBZMO: boolean
  b_max_los_data_for_prefilled_dest: BMaxLosDataForPrefilledDest
  b_partner_channel_id: string
  b_bookings_owned: string
  b_google_maps_key_params: string
  b_lang: string
  b_checkin_date: string
  b_checkout_date: string
  b_checkin_checkout_interval: number
  b_checkin_checkout_interval_in_weeks: number
  b_has_valid_dates: string
  b_has_available_rooms: boolean
  b_countrycode: string
  b_guest_country: string
  b_locale: string
  b_lang_for_url: string
  b_this_urchin: string
  b_flag_to_suggest: string
  b_companyname: string
  b_partner_vertical: string
  b_paid_traffic: number
  b_date_format: BDateFormat
  b_month_for_formatted_date: BMonthForFormattedDate
  b_weekday_formatted_date: BWeekdayFormattedDate
  b_time_format: BTimeFormat
  b_protocol: string
  auth_level: string
  b_user_auth_level_is_none: number
  b_check_ot_consent: number
  bui: Bui
  bb: Bb
  b_growls_close_fast: number
  fe_enable_login_with_phone_number: number
  b_hotel_history_count: number
  asyncLoader: AsyncLoader
  b_gallery_slide_onview: number
  fe_enable_fps_goal_with_value: number
  b_email_validation_regex: BEmailValidationRegex
  b_domain_end: string
  b_original_url: string
  b_this_url: string
  b_this_url_without_lang: string
  b_referrer: string
  b_acc_type: string
  b_req_login: string
  jst: Jst
  b_timestamp: number
  scripts_tracking: ScriptsTracking
  enable_scripts_tracking: number
  b_ufi: string
  setvar_affiliate_is_bookings2: number
  transl_close_x: string
  transl_checkin_title: string
  transl_checkout_title: string
  browser_lang: string
  b_hijri_calendar_available: boolean
  b_aid: string
  b_label: string
  b_sid: string
  b_dest_id: string
  ip_country: string
  country_currency: string
  b_selected_currency: string
  b_selected_currency_is_hotel_currency: string
  b_selected_language: string
  b_selected_language_country_flag: string
  pageview_id: string
  aid: string
  b_csrf_token: string
  b_show_user_accounts_features: number
  b_browser: string
  b_browser_version: string
  et_debug_level: string
  icons: string
  b_static_images: string
  b_currency_url: string
  b_currency_change_base_url: string
  b_languages_url: string
  b_weekdays: BWeekday[]
  b_group: BGroup[]
  b_group_rooms_wanted: number
  b_simple_weekdays: string[]
  b_simple_weekdays_for_js: string[]
  b_long_weekdays: string[]
  b_short_months: string[]
  b_short_months_abbr: string[]
  b_year_months: BYearMonths
  b_is_fb_safe: number
  b_is_app: number
  first_page_of_results: boolean
  b_partner_id: string
  b_is_destination_finder_supported: number
  b_is_dsf: number
  b_pr_param: string
  hotelAction: HotelAction
  feature_profile_split_sb_checkbox: number
  inandaround_more: string
  b_signup_iframe_url: string
  b_exclude_lang_firstname: number
  user_has_dates: number
  view_prices_enter_dates: string
  autocomplete_categories: AutocompleteCategories
  autocomplete_skip_suggestions: string
  autocomplete_counter_label: string
  autocomplete: Autocomplete
  lists: Lists
  touch_os: boolean
  calendar_days_allowed_number: number
  b_search_max_months: number
  b_run_ge_new_newsletter_login: number
  b_password_strength_msg: string[]
  b_passwd_min_length_error: string
  b_password_must_be_numeric: string
  b_bkng_nr_must_be_numeric: string
  b_blank_numeric_pin: string
  b_blank_bkng_nr: string
  password_cant_be_username: string
  b_show_passwd: string
  b_passwd_tooltip: string
  account_error_add_password: string
  password_needs_8: string
  error_sign_up_password_email_combo_01: string
  social_plugins_footer: number
  b_lazy_load_print_css: number
  print_css_href: string
  "component/dropdown-onload-shower/header_signin_prompt": ComponentDropdownOnloadShowerHeaderSigninPrompt
  b_hostname_signup: string
  b_nonsecure_hostname: string
  b_nonsecure_hostname_signup: string
  b_fd_searchresults_url_signup: string
  translation_customer_service_which_booking_no_specific: string
  stored_past_and_upcoming_bookings: any[]
  global_translation_tags: GlobalTranslationTags
  b_hotel_id: string
  b_hotel_name: string
  b_hotel_image_url_square60: string
  allRoomPhotos: AllRoomPhoto[]
  hotelPhotos: HotelPhoto[]
  b_hotelfeaturedreviews_url: string
  hp_gallery_lazyload: string
  hp_gallery_fade_speed: number
  hp_gallery_autoplay_speed: number
  b_run_hp_gallery_corner_navigation: boolean
  b_run_hp_booking_summary: boolean
  b_run_hp_gently_select_rooms: number
  run_hp_cheapest_room_reinforcement_double_occupancy: boolean
  hp_location_block: boolean
  b_run_hp_back_is_back: boolean
  b_from_action: string
  b_back_is_back_url: string
  b_run_hp_rt_lightbox_image_gallery_v2: boolean
  b_run_droom_hp_rt_lb_new_gallery: boolean
  b_run_droom_hp_increase_lb_photo_res: boolean
  b_run_hp_fixed_review_height: boolean
  run_hp_rt_lightbox: boolean
  run_hp_rt_lightbox_no_dates: boolean
  b_run_hp_rt_lightbox_image_gallery: boolean
  b_user_is_using_one_list_only: string
  defaultReviewsLanguage: string
  fe_reviews_base_params: FeReviewsBaseParams
  filterReviewsByTopic: number
  defaultReviewsTopic: any[]
  instalments_minimum_price: string
  payment_possible_in_instalments: string
  b_search_config: BSearchConfig
  wholesaler_configuration: WholesalerConfiguration
  tpi_search_config: TpiSearchConfig
  site_type: string
  days_to_checkin: string
  b_terms_and_conditions_url: string
  b_blocks_per_room_id: BBlocksPerRoomId[]
  b_gallery_has_photo_tags: boolean
  b_rooms_available_and_soldout: BRoomsAvailableAndSoldout[]
  b_cheapest_price_that_fits_search_eur: number
  b_photo_pid: string
  b_rackrates_monitoring_running: boolean
  b_wishlist_referrer: string
  b_reg_user_last_used_wishlist: string
  b_reg_user_wishlist_remaining: number
  is_user_center_bar: number
  b_site_experiment_user_center_bar: number
  b_reg_user_is_genius: string
  profile_menu: ProfileMenu
  accounting_config: AccountingConfig
  distance_config: string
  b_hotel_currencycode: string
  is_listview_page: boolean
  b_this_weekend_checkin: string
  b_this_weekend_checkout: string
  b_next_weekend_checkin: string
  b_next_weekend_checkout: string
  b_official_continent: string
  b_deals_continents: string
  b_messenger_url: string
  b_open_messenger: boolean
  b_is_asian_user: string
  b_days_to_checkin: string
  b_extra_ajax_headers: BExtraAjaxHeaders
  b_pricemode: number
  cn_modal_exp_eligible: string
  notification_squeaks: NotificationSqueaks
  fe_is_cname_cobrand_header_available: string
  wl_squeak: WlSqueak
  genius_vip_squeaks: GeniusVipSqueaks
  map_open_sr_hp_squeaks: MapOpenSrHpSqueaks
  trip_types_squeaks: TripTypesSqueaks
  insurance_squeaks: InsuranceSqueaks
  error: Error
  b_sb_autocomplete_predictions_url: string
  b_sb_autocomplete_predictions_method: string
  b_sb_googleplaces_carrier_url: string
  b_sb_googleplaces_carrier_method: string
  search_autocomplete_params: SearchAutocompleteParams
  b_fragment_url_html: string
  b_fragment_url_json: string
  b_has_maxotel_rooms: number
  b_hotel_blocks: number
  b_max_rooms_in_reservation: number
  you_can_book_at_most_x_rooms_with_this_hotel: string
  you_can_book_for_at_most_x_guests_per_reservation_with_this_hotel: string
  search_box_keep_children_ages_order: boolean
  fe_is_platinum_gold_amer_digital_retail: string
  fe_pp_web_shell_exp_tracking_allowed: number
  fe_number_of_all_rooms: string
  fe_hotel_id: number
  fe_is_platinum_gold_amer_technology: string
  fe_arp_searchbox_replatformed: number
  fe_show_fam_d_hp_rt_great_choice_no_fit_blackout: string
  fe_is_Family: string
  b_charges_has_tax_exceptions: number
  gallery_grid_migration_enabled: string
  fe_redirect_to_sr: number
  fe_property_has_private_beach: string
  room_symmetry_category_json: RoomSymmetryCategoryJson
  in_city_name: string
  fe_full_screen_side_reviews: string
  fe_is_platinum_gold_amer_partner_id: string
  property_name: string
  fe_property_is_beachfront: string
  fe_is_normal_user: number
  fe_sso_logout_state: string
  fe_feature_running_C360_PROPERTY_EVENT_TRACKER_VIA_FE: string
  fe_is_resort_heavy_ufi: string
  track_skip_links: number
  beach_team_pilot_data_loaded: string
  b_is_vacation_rental: string
  feature_track_reviews_on_view: string
  fe_loggedout_potential_genius_block_ids: string
  fe_is_platinum_gold_amer_travel_retail: string
  b_review_nr: number
  sp_use_loyalty_api: number
  fe_mrt_d_hp_rt_basket_integration: number
  fe_bbox_northeast_latitude: number
  fe_is_trainline_aid: string
  fe_agent_is_robot: number
  fe_is_platinum_gold_amer_affiliate_networks: string
  b_enable_property_highlights_list: string
  fe_is_incentives_ga_tracking_enabled: number
  fe_is_tt_d_sr_hp_show_all_beaches_in_map: string
  fe_is_hamer_rewards_desktop: string
  fe_aff_to_capla_comms: string
  fe_is_ski_sr_hp_lift_type_on_map_d_exp: string
  fe_pl_frag_rwdpl: number
  fe_sb_use_new_ski_icon: number
  b_tpi_soldout: number
  fe_property_has_free_private_beach: string
  fe_universal_perf_tracking_enabled: number
  fe_is_platinum_gold_amer_financial_services: string
  fe_show_fam_web_room_details_ceb_info: string
  b_is_tpi_exclusive_property: number
  b_tpi_eligible: number
  fe_google_one_tap_use_fedcm: number
  b_oauth_client_id: string
  fe_xpi_no_legacy_sync: number
  b_room_comparison_tracking_data: BRoomComparisonTrackingData
  b_sso_logout_url: string
  fe_is_platinum_gold_amer_media_content: string
  fe_dest_type: string
  fe_is_vacation_rental_new_definition: string
  fe_exp_rt_bp_abb_basket_v3_migration: string
  b_time_spent_track_pageview_id: string
  fe_enable_GA4_TRACKING_ON_LEGACY: string
  fe_bbox_northeast_longitude: number
  is_ski_async_op: number
  fe_hp_b_is_ski_experience: string
  fe_ba_link_capla: string
  fe_raw_entire_place: string
  fe_sp_enable_basic_inventory: string
  fe_run_google_one_tap: string
  fe_ski_show_op_in_hp: string
  fe_is_US: string
  b_hotel_class: number
  city_name: string
  fe_ski_destination_id: string
  fe_s_prprtyt: number
  fe_show_fam_web_hp_theme_park_benefits: string
  b_charges_excluded_charges_detail: string
  show_rocketmiles_av_frontend: number
  fe_is_platinum_gold_amer_airlines: string
  fe_location_www_pp_capla_map_cond: number
  b_site_info: BSiteInfo2
  fe_location_www_pp_map_styles_cond: number
  fe_is_in_beach_ufi: number
  b_time_spent_track: number
  fe_is_southwest_desktop: string
  fe_is_platinum_gold_amer_app_distribution: string
  fe_has_airport_access: any
  fe_is_mup_property: string
  b_3pi_thirdparty_api_failed: number
  b_analytics_tracking_string: string
  b_returning_status: number
  fe_property_has_paid_private_beach: string
  fe_use_header_mfe: number
  b_hiding_existing_beds: number
  fe_run_baidumap: string
  fe_login_page_accounts_portal_url: string
  fe_ufi: number
  fe_valid_chain: number
  b_sso_logout_callback_url: string
  fe_tt_blackout_map_entry_cn: string
  b_time_spent_track_uuid: string
  fe_bbox_southwest_longitude: number
  fe_b_beach_ufi: string
  fe_is_gallery_modal_redesign_bui: number
  b_time_spent_track_started_at: number
  fe_has_property_parking: FeHasPropertyParking
  fe_bbox_southwest_latitude: number
  js_tracking_url: string
  fe_gtm_src: string
  b_tpi_rooms_available: string
  fe_is_gallery_modal_migration: number
  fe_critical_path_surveys_copy_tag: string
  b_dqs_server: number
  b_hotel_chains: BHotelChain[]
  fe_track_is_sustainable_property: string
  b_occupancy: BOccupancy
  b_query_params_with_lang: string
  b_has_valid_dates_not_in_past: string
  b_dest_type: string
  is_rooms_table_splitter: boolean
  b_is_new: string
  b_referer_action: string
  is_rooms_table_rewrite: boolean
  b_map_center_latitude: number
  b_map_center_longitude: number
  b_query_params_no_ext: string
  b_server_role: string
  b_map_dest_type: string
  b_map_dest_id: string
  current_hotel: string
  map_more_params: string
  autocomplete_more_params: string
  touch_map_infowindow_close: string
  b_icons_url: string
  b_map_nights: string
  b_domestic_booker: string
  b_city_has_metro_access: string
  b_city_has_rail_access: string
  b_is_high_value_customer_ski_exp: string
  b_is_potential_high_value_customer_ski_exp: string
  b_is_low_present_value_customer_ski_exp: string
  b_is_new_value_customer_ski_exp: string
  b_is_no_fusion_match_value_customer_ski_exp: string
  b_url_start: string
  static_hostnames: string[]
  b_session_checkin_date: string
  b_session_checkout_date: string
  b_no_dates_mode: string
  b_months: BMonth[]
  b_this_year4: number
  b_this_month: number
  b_this_day: number
  date_format_acronym: string
  day: string
  sbox_day: string
  sbox_month: string
  month: string
  please_enter_your_check_in_date: string
  please_enter_your_check_out_date: string
  s_value_checkin_monthday_is_set: number
  s_value_checkin_year_month: string
  s_value_checkin_year_month_is_set: number
  s_value_checkout_monthday_is_set: number
  s_value_checkout_year_month: string
  s_value_checkout_year_month_is_set: number
  sb_flexi_srch_month_validation: string
  to_check_availability_please_enter_your_dates_of_stay: string
  checkout_date_not_after_checkin_date: string
  b_room_groups: any[]
  b_room_extrabeds: any[]
  b_show_all_inclusive_switch: number
  domain_for_book: string
  b_canonical_url: string
  b_canonical_url_delimiter: string
  b_query_params_delimiter: string
  group_room: string
  group_remove: string
  valdateDates_msg: string
  hide_bpg: string
  tab: string
  b_save_user_hotel_interactions: number
  b_room_group: any[]
  s_value_ss: string
  s_value_ss_raw: string
  close_button: string
  next_button: string
  prev_button: string
  book_button: string
  sunday_first: number
  experiment_popups_close: string
  a11y_dialog_content_start_text: string
  a11y_dialog_content_end_text: string
  city_name_en: string
  b_urlcity: string
  show_language_suggestion: ShowLanguageSuggestion
  b_is_group_search: string
  child_age_text: string
  b_stid: number
  b_new_ga_track: number
  prd_bpg_overlay_cs_link: string
  fe_new_perf_tracking: FeNewPerfTracking
  priceWatch: PriceWatch
  growl_triggers: GrowlTriggers
  google_analytics_tracking_enabled: number
  b_availability_checked: string
  b_multiple_destinations_found: string
  b_feature_running_TRACK_GA_EC_PROMO: boolean
  no_rooms_selected: number
  line_break: string
  rlm: string
  nbsp: string
  lrm: string
  one_dot_leader: string
  zwsp: string
  ga4_lib_init: boolean
  ga4_lib_handlers: boolean
  __headerInitialized: boolean
}

export interface BMaxLosDataForPrefilledDest {
  is_fullon: number
  experiment: string
  default_los: number
  extended_los: number
  max_allowed_los: number
  has_extended_los: number
}

export interface BDateFormat {
  day_short_month_between: string
  date_with_year: string
  date_with_weekday_to: string
  date_with_weekday_from: string
  day_month_year: string
  day_short_month_year_from: string
  short_date_without_year_range: string
  day_month_between: string
  in_month_with_year: string
  day_month: string
  month_name_only: string
  date_with_short_weekday_without_year: string
  date_with_weekday_time_until: string
  ux_day_month_on: string
  short_month_with_year: string
  day_short_month_year_time: string
  day_month_other: string
  day_month_year_on: string
  day_short_month_year_on: string
  day_month_from: string
  day_month_on: string
  range_from_long_date_time_until_long_date_time: string
  date_with_weekday_time_from_until: string
  day_short_month_year_until: string
  date_with_weekday_time_at: string
  numeric_day_month_year_from: string
  date_with_weekday_time_from: string
  day_short_month_year_between: string
  numeric_day_month_year: string
  date_with_weekday_with_markers: string
  long_date_range_both_years: string
  day_short_month_time: string
  numeric_day_month_year_between: string
  date_range_with_short_weekday_short_month: string
  day_short_month_year_time_between: string
  day_month_year_between: string
  short_month_only: string
  numeric_day_month_year_until: string
  short_date: string
  day_month_year_time_before: string
  short_date_with_weekday_without_year: string
  numeric_date_range: string
  day_of_month_only: string
  numeric_date_range_both_years: string
  day_short_month_year_other: string
  short_weekday_only: string
  day_month_year_other: string
  numeric_day_month_year_time_before: string
  numeric_date: string
  day_month_year_from: string
  date_with_short_weekday_with_year: string
  date_with_weekday: string
  day_month_year_until: string
  day_short_month_year: string
  day_short_month_time_between: string
  month_with_year: string
  numeric_day_month_year_on: string
  short_date_with_weekday: string
  from_month_with_year: string
  date_without_year: string
  ux_day_month: string
  day_month_until: string
  short_date_without_year: string
}

export interface BMonthForFormattedDate {
  "1": N1
  "2": N2
  "3": N3
  "4": N4
  "5": N5
  "6": N6
  "7": N7
  "8": N8
  "9": N9
  "10": N10
  "11": N11
  "12": N12
}

export interface N1 {
  on_day_month: string
  to_month_lc: string
  name_only: string
  name_to: string
  name_from: string
  name_with_year_only: string
  name: string
  in_month_lc: string
  day_to: string
  short_name: string
  short_name_only: string
  name_other: string
  genitive_uc: string
  name_def_article_uc: string
  short_name_uc: string
  genitive_lc: string
  name_in: string
  month_2: string
  name_def_article_lc: string
  month_1: string
  name_lc: string
  name_uc: string
}

export interface N2 {
  name_def_article_lc: string
  month_2: string
  name_lc: string
  month_1: string
  name_uc: string
  short_name_uc: string
  name_in: string
  genitive_lc: string
  day_to: string
  short_name_only: string
  short_name: string
  name_other: string
  genitive_uc: string
  name: string
  in_month_lc: string
  name_def_article_uc: string
  name_only: string
  name_to: string
  name_from: string
  on_day_month: string
  to_month_lc: string
  name_with_year_only: string
}

export interface N3 {
  name: string
  in_month_lc: string
  genitive_uc: string
  name_other: string
  day_to: string
  short_name_only: string
  short_name: string
  name_def_article_uc: string
  on_day_month: string
  to_month_lc: string
  name_to: string
  name_from: string
  name_only: string
  name_with_year_only: string
  month_2: string
  name_def_article_lc: string
  name_lc: string
  month_1: string
  name_uc: string
  short_name_uc: string
  genitive_lc: string
  name_in: string
}

export interface N4 {
  name_only: string
  name_from: string
  name_to: string
  short_name_uc: string
  to_month_lc: string
  on_day_month: string
  name_in: string
  name_with_year_only: string
  genitive_lc: string
  short_name_only: string
  short_name: string
  month_2: string
  name_def_article_lc: string
  name_other: string
  genitive_uc: string
  in_month_lc: string
  name: string
  name_def_article_uc: string
  name_uc: string
  month_1: string
  name_lc: string
}

export interface N5 {
  in_month_lc: string
  name: string
  short_name_only: string
  short_name: string
  name_def_article_lc: string
  month_2: string
  name_other: string
  genitive_uc: string
  name_uc: string
  name_lc: string
  month_1: string
  name_def_article_uc: string
  short_name_uc: string
  on_day_month: string
  to_month_lc: string
  name_only: string
  name_from: string
  name_to: string
  genitive_lc: string
  name_in: string
  name_with_year_only: string
}

export interface N6 {
  name_uc: string
  month_1: string
  name_lc: string
  name_def_article_uc: string
  in_month_lc: string
  name: string
  short_name_only: string
  short_name: string
  name_def_article_lc: string
  month_2: string
  name_other: string
  genitive_uc: string
  genitive_lc: string
  name_in: string
  name_with_year_only: string
  short_name_uc: string
  to_month_lc: string
  on_day_month: string
  name_only: string
  name_from: string
  name_to: string
}

export interface N7 {
  short_name_uc: string
  to_month_lc: string
  on_day_month: string
  name_only: string
  name_to: string
  name_from: string
  genitive_lc: string
  name_in: string
  name_with_year_only: string
  name: string
  in_month_lc: string
  name_def_article_lc: string
  month_2: string
  short_name: string
  short_name_only: string
  genitive_uc: string
  name_other: string
  month_1: string
  name_lc: string
  name_uc: string
  name_def_article_uc: string
}

export interface N8 {
  name_with_year_only: string
  name_in: string
  genitive_lc: string
  name_from: string
  name_to: string
  name_only: string
  to_month_lc: string
  on_day_month: string
  short_name_uc: string
  name_def_article_uc: string
  name_uc: string
  month_1: string
  name_lc: string
  name_other: string
  genitive_uc: string
  short_name: string
  short_name_only: string
  month_2: string
  name_def_article_lc: string
  in_month_lc: string
  name: string
}

export interface N9 {
  name_def_article_uc: string
  name_uc: string
  name_lc: string
  month_1: string
  short_name: string
  short_name_only: string
  name_def_article_lc: string
  month_2: string
  genitive_uc: string
  name_other: string
  in_month_lc: string
  name: string
  name_in: string
  name_with_year_only: string
  genitive_lc: string
  name_only: string
  name_from: string
  name_to: string
  short_name_uc: string
  to_month_lc: string
  on_day_month: string
}

export interface N10 {
  name_other: string
  genitive_uc: string
  short_name_only: string
  short_name: string
  name_def_article_lc: string
  month_2: string
  in_month_lc: string
  name: string
  name_def_article_uc: string
  name_uc: string
  month_1: string
  name_lc: string
  name_from: string
  name_to: string
  name_only: string
  on_day_month: string
  to_month_lc: string
  short_name_uc: string
  name_with_year_only: string
  name_in: string
  genitive_lc: string
}

export interface N11 {
  genitive_lc: string
  name_with_year_only: string
  name_in: string
  on_day_month: string
  to_month_lc: string
  short_name_uc: string
  name_to: string
  name_from: string
  name_only: string
  month_1: string
  name_lc: string
  name_uc: string
  name_def_article_uc: string
  name: string
  in_month_lc: string
  name_other: string
  genitive_uc: string
  name_def_article_lc: string
  month_2: string
  short_name_only: string
  short_name: string
}

export interface N12 {
  genitive_lc: string
  name_in: string
  name_with_year_only: string
  short_name_uc: string
  to_month_lc: string
  on_day_month: string
  name_only: string
  name_to: string
  name_from: string
  name_lc: string
  month_1: string
  name_uc: string
  name_def_article_uc: string
  name: string
  in_month_lc: string
  name_def_article_lc: string
  month_2: string
  short_name_only: string
  short_name: string
  name_other: string
  genitive_uc: string
}

export interface BWeekdayFormattedDate {
  "0": N0
  "1": N13
  "2": N22
  "3": N32
  "4": N42
  "5": N52
  "6": N62
  "7": N72
  "8": N82
}

export interface N0 {
  short_uc: string
  shortest: string
  name_from: string
  name_to: string
  name_other_uc: string
  short: string
  name_uc: string
  name_lc: string
  name_other: string
  name_from_preposition: string
  name_on: string
  name: string
}

export interface N13 {
  shortest: string
  short_uc: string
  short: string
  name_other_uc: string
  name_to: string
  name_from: string
  name_lc: string
  name_uc: string
  name: string
  name_on: string
  name_from_preposition: string
  name_other: string
}

export interface N22 {
  name_other_uc: string
  short: string
  name_from: string
  name_to: string
  shortest: string
  short_uc: string
  name_on: string
  name: string
  name_other: string
  name_from_preposition: string
  name_uc: string
  name_lc: string
}

export interface N32 {
  short_uc: string
  shortest: string
  name_to: string
  name_from: string
  name_other_uc: string
  short: string
  name_lc: string
  name_uc: string
  name_other: string
  name_from_preposition: string
  name: string
  name_on: string
}

export interface N42 {
  shortest: string
  short_uc: string
  name_other_uc: string
  short: string
  name_to: string
  name_from: string
  name_lc: string
  name_uc: string
  name: string
  name_on: string
  name_other: string
  name_from_preposition: string
}

export interface N52 {
  name_other: string
  name_from_preposition: string
  name: string
  name_on: string
  name_lc: string
  name_uc: string
  name_to: string
  name_from: string
  name_other_uc: string
  short: string
  short_uc: string
  shortest: string
}

export interface N62 {
  name_from: string
  name_to: string
  name_other_uc: string
  short: string
  short_uc: string
  shortest: string
  name_other: string
  name_from_preposition: string
  name_on: string
  name: string
  name_uc: string
  name_lc: string
}

export interface N72 {
  short_uc: string
  shortest: string
  name_from: string
  name_to: string
  name_other_uc: string
  short: string
  name_uc: string
  name_lc: string
  name_other: string
  name_from_preposition: string
  name_on: string
  name: string
}

export interface N82 {
  name_to: string
  name_from: string
  short: string
  name_other_uc: string
  short_uc: string
  shortest: string
  name_from_preposition: string
  name_other: string
  name: string
  name_on: string
  name_lc: string
  name_uc: string
}

export interface BTimeFormat {
  AM_symbol: AmSymbol
  PM_symbol: PmSymbol
  time: Time
  time_12: Time12
  time_24: Time24
}

export interface AmSymbol {
  name: string
}

export interface PmSymbol {
  name: string
}

export interface Time {
  name: string
}

export interface Time12 {
  name: string
}

export interface Time24 {
  name: string
}

export interface Bui {
  color: Color
}

export interface Color {
  bui_color_grayscale_dark: string
  bui_color_grayscale: string
  bui_color_grayscale_light: string
  bui_color_grayscale_lighter: string
  bui_color_grayscale_lightest: string
  bui_color_primary_dark: string
  bui_color_primary: string
  bui_color_primary_light: string
  bui_color_primary_lighter: string
  bui_color_primary_lightest: string
  bui_color_complement_dark: string
  bui_color_complement: string
  bui_color_complement_light: string
  bui_color_complement_lighter: string
  bui_color_complement_lightest: string
  bui_color_callout_dark: string
  bui_color_callout: string
  bui_color_callout_light: string
  bui_color_callout_lighter: string
  bui_color_callout_lightest: string
  bui_color_destructive_dark: string
  bui_color_destructive: string
  bui_color_destructive_light: string
  bui_color_destructive_lighter: string
  bui_color_destructive_lightest: string
  bui_color_constructive_dark: string
  bui_color_constructive: string
  bui_color_constructive_light: string
  bui_color_constructive_lighter: string
  bui_color_constructive_lightest: string
  bui_color_action: string
  bui_color_white: string
  bui_color_black: string
}

export interface Bb {
  ibb: string
  uibb: string
  ibbta: string
  itp: string
  iuibb: string
  bme: string
  euibb: string
  tp: string
}

export interface AsyncLoader {
  async_assistant_entrypoint_css: string
  async_assistant_entrypoint_js: string
  async_atlas_places_js: string
  async_atlas_v2_cn_js: string
  async_atlas_v2_non_cn_js: string
  image_gallery_js: string
  image_gallery_css: string
  async_lists_js: string
  async_atlas_css: string
  async_hp_atlas_map_js: string
  async_wpm_overlay_css: string
  async_wpm_overlay_js: string
  async_slider_view_js: string
  async_slider_view_css: string
  async_beach_team_pilot_js: string
  async_beach_team_pilot_css: string
  async_room_lightbox_js: string
  empty: string
}

export interface BEmailValidationRegex { }

export interface Jst {
  loading: boolean
}

export interface ScriptsTracking {
  atlas: Atlas
  atlas_cst: AtlasCst
  bhc: Bhc
  calendar2: Calendar2
  hotel: Hotel
  jquery: Jquery
  main: Main
  core_deps: CoreDeps
  searchbox: Searchbox
  raf: Raf
}

export interface Atlas {
  loaded: boolean
  run: boolean
}

export interface AtlasCst {
  loaded: boolean
  run: boolean
}

export interface Bhc {
  loaded: boolean
  run: boolean
}

export interface Calendar2 {
  loaded: boolean
  run: boolean
}

export interface Hotel {
  loaded: boolean
  run: boolean
}

export interface Jquery {
  loaded: boolean
  run: boolean
}

export interface Main {
  loaded: boolean
  run: boolean
}

export interface CoreDeps {
  loaded: boolean
  run: boolean
}

export interface Searchbox {
  loaded: boolean
  run: boolean
}

export interface Raf {
  loaded: boolean
  run: boolean
}

export interface BWeekday {
  b_is_weekend?: number
  b_number?: number
  name?: string
  short?: string
  shorter?: string
  shortest?: string
}

export interface BGroup {
  guests: number
  children: number
  ages: any[]
}

export interface BYearMonths {
  "2024-11": N202411
  "2024-12": N202412
  "2025-1": N20251
  "2025-2": N20252
  "2025-3": N20253
  "2025-4": N20254
  "2025-5": N20255
  "2025-6": N20256
  "2025-7": N20257
  "2025-8": N20258
  "2025-9": N20259
  "2025-10": N202510
  "2025-11": N202511
  "2025-12": N202512
  "2026-1": N20261
  "2026-2": N20262
}

export interface N202411 {
  name: string
}

export interface N202412 {
  name: string
}

export interface N20251 {
  name: string
}

export interface N20252 {
  name: string
}

export interface N20253 {
  name: string
}

export interface N20254 {
  name: string
}

export interface N20255 {
  name: string
}

export interface N20256 {
  name: string
}

export interface N20257 {
  name: string
}

export interface N20258 {
  name: string
}

export interface N20259 {
  name: string
}

export interface N202510 {
  name: string
}

export interface N202511 {
  name: string
}

export interface N202512 {
  name: string
}

export interface N20261 {
  name: string
}

export interface N20262 {
  name: string
}

export interface HotelAction {
  showReviews: number
  minReviews: number
  hotelName: string
  pageLang: string
  hotelCountry: string
  has_business_reviews: boolean
}

export interface AutocompleteCategories {
  city: string
  region: string
  airport: string
  hotel: string
  landmark: string
  country: string
  district: string
  theme: string
}

export interface Autocomplete {
  property_nearby: string
  properties_nearby: string
  hotel: string
  hotels: string
  hotels_nearby: string
}

export interface Lists {
  collection: Collection[]
}

export interface Collection {
  id: string
  name: string
  hotels_count: string
}

export interface ComponentDropdownOnloadShowerHeaderSigninPrompt {
  b_action: string
}

export interface GlobalTranslationTags {
  line_break: string
  rlm: string
  nbsp: string
  lrm: string
  one_dot_leader: string
  zwsp: string
}

export interface AllRoomPhoto {
  id: string
  thumb_url: string
  large_url: string
  associated_rooms: string[]
  orientation: string
  created: string
  grid: Grid
}

export interface Grid {
  photo_width: number
  photo_height: number
}

export interface HotelPhoto {
  id: string
  thumb_url: string
  large_url: string
  highres_url?: string
  orientation?: string
  created?: string
  grid: Grid2
  associated_rooms?: string[]
  name?: string
  caption_right?: string
  caption_left?: string
  room_id?: string
  thumb_contains?: string
  thumb_className?: string
  contains?: string
  className?: string
  verticalAlign?: string
}

export interface Grid2 {
  photo_width: number
  photo_height: number
  content?: string
  contains?: string
  thumb_contains?: string
}

export interface FeReviewsBaseParams {
  score: string
  dist: string
  rows: string
  offset: string
  topics: any[]
  lang: any[]
  type: string[]
  page: string
  country: string
  rurl: string
  query: string
  sort: string
}

export interface BSearchConfig {
  autosplit: number
  b_nr_rooms_needed: number
  traveller_segment: string
  b_additional_channels: number[]
  b_rooms: BRoom[]
  b_adults_total: number
  b_pets_total: any
  b_children_ages_total: any[]
  b_abnormal_params: number
  b_is_group_search: number
  b_children_total: number
}

export interface BRoom {
  b_children_ages: any[]
  b_adults: number
  b_children: number
  b_room_order: number
}

export interface WholesalerConfiguration {
  search_config_adults: string
  search_config_children: string
  search_config_rooms: string
  accommodation_type_id: string
  url: string
  payment_methods_url: string
  tpi_av_id: string
  b_3pi_thirdparty_api_failed: string
  b_3pi_show_room_in_rt: string
  b_send_first_room_id_to_bp_feature: number
  business_bookers: BusinessBookers
  availability_exp: AvailabilityExp
  fe_tpi_breakfast_score: string
  fe_tpi_breakfast_review_nr: string
  location_score: string
  tpi_track_ajax_failures: number
  tpi_hp_no_photo_squeak_name: string
  fe_max_occupants: number
  b_checkin_checkout_interval: number
  b_checkin_checkout_interval_is_1: number
  b_show_citizen_vat_message: number
  b_tpi_optional_mealplans: string
}

export interface BusinessBookers {
  b_is_bbtool_user: string
  b_user_is_business_booker: string
  b_inferred_user_is_business_booker: string
}

export interface AvailabilityExp {
  geo: string
}

export interface TpiSearchConfig {
  autosplit: number
  b_nr_rooms_needed: number
  traveller_segment: string
  b_additional_channels: number[]
  b_rooms: BRoom2[]
  b_adults_total: number
  b_pets_total: any
  b_children_ages_total: any[]
  b_abnormal_params: number
  b_is_group_search: number
  b_children_total: number
}

export interface BRoom2 {
  b_children_ages: any[]
  b_adults: number
  b_children: number
  b_room_order: number
}

export interface BBlocksPerRoomId {
  b_blocks: BBlock[]
}

export interface BBlock {
  b_block_id: string
  b_room_id: string
}

export interface BRoomsAvailableAndSoldout {
  b_blocks: BBlock2[]
  b_roomtype_id: number
  b_has_room_inventory: number
  b_id: number
  b_name: string
}

export interface BBlock2 {
  b_avg_price_per_night_eur: string
  b_nr_stays: number
  b_is_cfar: number
  b_raw_price: string
  b_max_persons: number
  b_rate_is_genius: number
  b_cancellation_type: string
  b_stay_prices: BStayPrice[]
  b_mealplan_included_name?: string
  b_price_breakdown_simplified: BPriceBreakdownSimplified
  b_price: string
  b_block_id: string
  b_cfar_tc_link: string
  b_book_now_pay_later?: number
}

export interface BStayPrice {
  b_stays: number
  b_price_per_night: string
  b_price: string
  b_local_price: number
  b_cfar_raw_price: number
  b_cfar_price: number
  b_raw_price: any
}

export interface BPriceBreakdownSimplified {
  b_price_display_config: BPriceDisplayConfig[]
  b_vm_products: any[]
  b_tax_exception: number
  b_headline_price_amount: number
  b_excluded_charges_amount: number
  b_reward_credit_amount: number
  b_strikethrough_price_amount: number
}

export interface BPriceDisplayConfig {
  key: string
  value: number
}

export interface ProfileMenu {
  b_user_auth_level: number
  b_domain_for_app: string
  b_query_params_with_lang_no_ext: string
  b_travel_comm_url_with_lang: string
  b_action: string
  b_site_info: BSiteInfo
  b_site_type: string
  b_companyname: string
  b_reg_user_full_name: string
  b_is_genius_branded: string
  b_reg_user_is_genius: string
  b_genius_dashboard_expiry_destfinder_url: string
  b_reg_user_last_used_wishlist: string
  b_genius_product_page_url: string
  b_reg_user_five_bookings_challenge: string
  b_reg_user_detail_name_email_hash: string
  b_user_is_grap_eligible: string
  b_grap_remove_raf_checks: number
  b_is_bbtool_admin: string
  b_is_bbtool_user: string
  fe_bbtool_permission_is_connected_to_bbtool: string
  fe_this_url_travel_purpose_business: string
  fe_this_url_travel_purpose_leisure: string
  fe_reservations_url_travel_purpose_business: string
  fe_reservations_url_travel_purpose_leisure: string
  fe_my_settings_url: string
  fe_my_settings_url_travel_purpose_business: string
  fe_my_settings_url_travel_purpose_leisure: string
  fe_bbtool_can_see_tool_promos: string
  fe_bbtool_blackout_user_company: string
  fe_bbtool_redirect_personal_to_index: number
  b_reg_user_company_name: string
  b_reg_user_company_name_escaped: string
  b_reg_user_companyjoin_url: string
  b_bbtool_product_page_url: string
  b_is_ie7: string
  b_this_url: string
  b_lang_for_url: string
  b_secure_hostname: string
  b_nonsecure_hostname: string
  b_query_params_with_lang: string
  b_query_params_delimiter: string
  b_reg_user_detail_dashboard_url: string
  b_is_reg_user_city_guide_in_lang_available: string
  b_aspiring_user_fifth_booking_ufi: string
  b_reg_user_aspiring_data: string
  b_dummy_var_for_trailing_comma: boolean
  b_ip_country: string
  b_guest_country: string
  b_agent_is_no_robot: number
  b_page_name: string
  b_landingpage_theme_type: string
  b_user_has_mobile_app: string
  b_aid: number
  b_label: string
  fe_show_travel_communities_menu_item: number
  fe_user_can_see_company_reservations: any
  b_oauth_client_id: string
  b_sso_logout_url: string
  b_sso_logout_callback_url: string
  fe_sso_logout_state: string
  fe_blackout_mydashboard: string
  fe_user_menu_aspiring_genius_link: boolean
}

export interface BSiteInfo {
  is_iam_auth_allowed: number
  is_bookings_owned: number
}

export interface AccountingConfig {
  html_symbol: HtmlSymbol
  currency_separator: CurrencySeparator
  decimal_separator: DecimalSeparator
  num_decimals: NumDecimals
  group_separator: GroupSeparator
  symbol_position: SymbolPosition
}

export interface HtmlSymbol {
  PLN: string
  RON: string
  IDR: string
  BRL: string
  SGD: string
  ARS: string
  CLP: string
  USD: string
  HKD: string
  INR: string
  JPY: string
  ILS: string
  EUR: string
  PHP: string
  XPF: string
  CZK: string
  TRY: string
  GBP: string
}

export interface CurrencySeparator {
  USD: string
  GBP: string
  default: string
  JPY: string
}

export interface DecimalSeparator {
  default: string
}

export interface NumDecimals {
  LYD: number
  IDR: number
  RUB: number
  HUF: number
  KWD: number
  MZM: number
  default: number
  KRW: number
  CLP: number
  COP: number
  VND: number
  GNF: number
  VUV: number
  OMR: number
  RWF: number
  KMF: number
  PYG: number
  MGA: number
  UGX: number
  IQD: number
  XOF: number
  BYR: number
  XPF: number
  ECS: number
  TJR: number
  LAK: number
  XAF: number
  ISK: number
  JOD: number
  BHD: number
  JPY: number
  AFA: number
  TMM: number
  TND: number
  BIF: number
  DJF: number
  TWD: number
}

export interface GroupSeparator {
  default: string
}

export interface SymbolPosition {
  PLN: string
  CZK: string
  default: string
  RON: string
}

export interface BExtraAjaxHeaders { }

export interface NotificationSqueaks { }

export interface WlSqueak {
  open_wishlist_from_hp: string
  create_wishlist_from_hp: string
}

export interface GeniusVipSqueaks {
  gnsSpun_bannerView_hp: string
  gnsSpun_bannerCtaClick_hp: string
  gnsSpun_modalView_hp: string
  gnsSpun_modalCtaClick_hp: string
  gnsInsCrd_bannerView_hp: string
  gnsInsCrd_bannerCtaClick_hp: string
  gnsInsCrd_modalView_hp: string
  gnsInsCrd_modalCtaClick_hp: string
  gnsBkun_bannerView_hp: string
  gnsBkun_bannerCtaClick_hp: string
  gnsBkun_modalView_hp: string
  gnsBkun_modalCtaClick_hp: string
  gnsInsDisc_bannerView_hp: string
  gnsInsDisc_bannerCtaClick_hp: string
  gnsOnbe_modalView_hp: string
  gnsOnbe_modalCtaClick_hp: string
}

export interface MapOpenSrHpSqueaks {
  mapOpenInSearchResultsOrHotelPage: string
}

export interface TripTypesSqueaks {
  ski_hp_d_map_no_lift_markers: string
  beach_hp_d_map_no_beach_markers: string
  beach_hp_d_map_no_beaches_nearby: string
  beach_hp_d_panel_response_error: string
  beach_hp_d_async_scripts_failed: string
  ski_hp_d_panel_response_error: string
  dummyvar: boolean
}

export interface InsuranceSqueaks {
  mfe_ready: string
  quote_reference_received: string
  insurance_received: string
}

export interface Error {
  checkin_date_in_the_past: CheckinDateInThePast
  checkin_date_invalid: CheckinDateInvalid
  checkin_date_to_far_in_the_future: CheckinDateToFarInTheFuture
  checkout_date_invalid: CheckoutDateInvalid
  checkout_date_more_than_30_days_after_checkin: CheckoutDateMoreThan30DaysAfterCheckin
  checkout_date_not_after_checkin_date: CheckoutDateNotAfterCheckinDate
  not_specific_enough: NotSpecificEnough
  checkin_in_past_error_suggest_tonight: CheckinInPastErrorSuggestTonight
  hp_dates_in_the_past: HpDatesInThePast
  hp_same_day_checkin_checkout: HpSameDayCheckinCheckout
}

export interface CheckinDateInThePast {
  name: string
}

export interface CheckinDateInvalid {
  name: string
}

export interface CheckinDateToFarInTheFuture {
  name: string
}

export interface CheckoutDateInvalid {
  name: string
}

export interface CheckoutDateMoreThan30DaysAfterCheckin {
  name: string
}

export interface CheckoutDateNotAfterCheckinDate {
  name: string
}

export interface NotSpecificEnough {
  name: string
}

export interface CheckinInPastErrorSuggestTonight {
  name: string
}

export interface HpDatesInThePast {
  name: string
}

export interface HpSameDayCheckinCheckout {
  name: string
}

export interface SearchAutocompleteParams {
  v: string
  lang: string
  sid: string
  aid: string
  pid: string
  stype: string
  src: string
  eb: string
  e_obj_labels: string
  context_dest_type: string
  context_dest_id: string
  from_hotel: number
  e_tclm: number
  add_themes: string
  themes_match_start: string
  include_synonyms: string
}

export interface RoomSymmetryCategoryJson {
  "71812401": string
  "71812405": string
  "71812406": string
}

export interface BRoomComparisonTrackingData {
  search_config: SearchConfig
  first_room_id: number
  track_view_stages: number
  second_room_id: number
}

export interface SearchConfig {
  num_rooms: number
  num_adults: number
  num_children: number
}

export interface BSiteInfo2 {
  is_iam_auth_allowed: number
  is_bookings_owned: number
}

export interface FeHasPropertyParking {
  like_policy: number
  b_onsite: number
  old_type: number
  b_slug: string
  location: number
  has_equiv: number
  new_type: number
  b_new_facility_type: number
  b_offsite: number
  b_name_en: string
  from: string
  b_parent_id: number
  b_id: number
  b_facility_type: number
  b_free: string
  b_paid: string
  name: string
  b_kind: string
  price_status: number
}

export interface BHotelChain {
  b_chain_type_id: number
  b_num_reviews_properties: number
  b_chain_id: number
  b_url: any
  b_num_reviews_countries: number
  b_num_reviews: number
  b_num_countries: number
  b_brand_year: number
  b_num_properties: number
  b_name: string
  b_reviews_usp: BReviewsUsp
  b_logo_std: string
  b_is_global_chain: number
  b_trans: any
  b_adf_id: number
  b_avg_review_score: number
  b_id: number
}

export interface BReviewsUsp {
  staff: Staff
  bed_comfort: BedComfort
  hotel_breakfast: HotelBreakfast
  cleanliness: Cleanliness
  value_for_money: ValueForMoney
  valid_review_types_for_usp: any[]
  location: Location
}

export interface Staff {
  properties_with_score: number
  properties_with_score_above_8: number
  score_percentage: number
}

export interface BedComfort {
  score_percentage: number
  properties_with_score: number
  properties_with_score_above_8: number
}

export interface HotelBreakfast {
  score_percentage: number
  properties_with_score: number
  properties_with_score_above_8: number
}

export interface Cleanliness {
  properties_with_score_above_8: number
  properties_with_score: number
  score_percentage: number
}

export interface ValueForMoney {
  properties_with_score_above_8: number
  properties_with_score: number
  score_percentage: number
}

export interface Location {
  properties_with_score: number
  properties_with_score_above_8: number
  score_percentage: number
}

export interface BOccupancy {
  adults: number
  children: number
  guests: number
}

export interface BMonth {
  b_number: number
  name: string
}

export interface ShowLanguageSuggestion {
  transl_change_page_lang_to_x: string
  browser_lang_select_suggested_lang: string
  suggested_lang_select: string
  suggested_lang_flag: string
}

export interface FeNewPerfTracking {
  first_visit: string
  params: Params
  setup: boolean
}

export interface Params {
  cdn: string
  dc: string
  bo: string
  route: string
}

export interface PriceWatch {
  b_price_alert_canceled: string
  b_price_alert_all_canceled: string
}

export interface GrowlTriggers {
  abandoned_rooms_table: AbandonedRoomsTable
}

export interface AbandonedRoomsTable {
  text: string
  textLabel: string
  stay: boolean
  stayTime: number
  type: string
  close: string
  injectHTML: string
  destination: string
  zindex: string
  scroll: boolean
  isAutomatic: boolean
}
